README.md
docs/DeveloperGuide.md
docs/_config.yml
docs/_sass/minima/_base.scss

Update NFR, README.md, _config.yml 

---

docs/DeveloperGuide.md

Close #38.
As follow:
```
<details>
<summary><b>Title</b></summary>
<pre> 
<b>MSS</b>
1. Text.
2. Text.
<3 spacing>Sub text.
<b>Extensions</b>
* #a. Text.
<5 spacing>* n#1. Sub text.
<   11 spacing   >Sub sub text.
</pre>
</details>  
```
Other changes:
- removed empty lines in between.
- assigned indenpendent use case numbering range for different feature tracks.
- renamed all duke driver to system.

Standardise use case formats

---

src/main/resources/view/MainWindow.fxml

Statistic button to open a new window to display the current statistics

Add Statistic Button to main window

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/model/jobs/DeliveryJob.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/json/model/JsonAdaptedDeliveryJob.java
src/test/java/seedu/address/testutil/TypicalDeliveryJobs.java

Add sender to delivery job model

---

README.md
docs/AboutUs.md
docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/logic/commands/TimetableDateCommand.java
src/main/java/seedu/address/logic/parser/DukeDriverParser.java

* Add timetable date command to main window 
* Update UG, DG, README

Add timetable date command to main window, update Ha Duong responsibilities

---

src/main/java/seedu/address/ui/ReminderListWindow.java
src/test/java/seedu/address/logic/commands/ExitCommandTest.java

***Does not fix the original issue yet!!
This pr fixes another bug in ReminderListWindow.
Will use this pr to fix all the bugs of ReminderListWindow

Fix ReminderListWindow bug

---

src/main/java/seedu/address/logic/parser/jobs/AddDeliveryJobCommandParser.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/jobs/DeliveryDate.java
src/main/java/seedu/address/model/jobs/DeliveryJob.java
src/main/java/seedu/address/model/jobs/DeliverySlot.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/json/model/JsonAdaptedDeliveryJob.java
src/main/java/seedu/address/ui/jobs/DeliveryJobCard.java
src/main/java/seedu/address/ui/jobs/DeliveryJobFullDetail.java
src/main/resources/view/DeliveryJobListCard.fxml
src/main/resources/view/FullDeliveryJobDetailPane.fxml
src/test/java/seedu/address/testutil/TypicalDeliveryJobs.java

Available
```
getDeliveryDate(): Optional<DeliveryDate>
getDeliverySlot(): Optional<DeliverySlot>
isScheduled(): boolean
```

Add delivery date attribute to model

---

docs/DeveloperGuide.md

Fix DG formatting

---

src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
src/main/java/seedu/address/logic/commands/reminder/ListReminderCommand.java
src/main/java/seedu/address/logic/parser/DukeDriverParser.java
src/main/java/seedu/address/logic/parser/reminder/AddReminderParser.java
src/main/java/seedu/address/logic/parser/reminder/DeleteReminderParser.java
src/main/java/seedu/address/ui/UiManager.java
src/main/java/seedu/address/ui/notification/BackgroundNotificationScheduler.java
src/main/java/seedu/address/ui/notification/BackgroundReminderTask.java
src/main/java/seedu/address/ui/notification/NotificationManager.java

Notifications of reminders only showed when the app start up. Having the notification show the reminders at every hour helps with informing the user better.
Let's:
* Utilise TimerTask and Timer to schedule a check in the reminder list at every clock hour
I use TimerTask and Timer because running a Thread that constantly checks the current time blocks the app and causes it to hang.

Notification of reminders can show at every clock hour.

---

docs/DeveloperGuide.md

Update the DG with design details for Statistics feature 
More details to be added later

Update DG draft for stats window

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/person/AddressBookWindow.java

New `execute(cmd: Command)` in logic class for UI layer access.

Extend execute in logic to accept command as arg

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/jobs/AddDeliveryJobCommand.java
src/main/java/seedu/address/logic/commands/jobs/CompleteDeliveryJobCommand.java
src/main/java/seedu/address/logic/commands/jobs/DeleteDeliveryJobCommand.java
src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
src/main/java/seedu/address/logic/parser/DukeDriverParser.java
src/main/java/seedu/address/logic/parser/jobs/AddDeliveryJobCommandParser.java
src/main/java/seedu/address/logic/parser/jobs/CompleteDeliveryJobCommandParser.java
src/main/java/seedu/address/model/jobs/DeliveryJob.java
src/main/java/seedu/address/model/jobs/DeliveryJobContainsKeywordsPredicate.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/jobs/DeliveryJobListPanel.java
src/main/resources/view/MainWindow.fxml

close #97 
close #107 
close #108
fix #134

Add support for set job as not/ complete

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
src/main/java/seedu/address/model/jobs/DeliveryJob.java
src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
src/main/java/seedu/address/ui/jobs/DeliveryJobDetailPane.java
src/main/resources/view/AddDeliveryJobWindow.fxml
src/main/resources/view/DayDeliveryJobListCard.fxml
src/main/resources/view/DeliveryJobDetailPane.fxml
src/main/resources/view/DeliveryJobListCard.fxml
src/main/resources/view/MainWindow copy.fxml
src/main/resources/view/MainWindow.fxml
src/main/resources/view/UnscheduleWindow.fxml

fix issue with opening multiple addressbook windows for person selection.
fix #145, fix #144, add null handler for invalid datafile.
close #146, add description to choice box.

[AddJobWindow] Refine optional job schedule validation logic

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/jobs/AddDeliveryJobCommand.java
src/main/java/seedu/address/logic/commands/timetable/TimetableCompletedCommand.java
src/main/java/seedu/address/logic/parser/DukeDriverParser.java
src/main/java/seedu/address/logic/parser/jobs/AddDeliveryJobCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/jobs/DeliveryJob.java
src/main/java/seedu/address/model/jobs/DeliverySlot.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/StatisticsWindow.java
src/main/java/seedu/address/ui/jobs/DayDeliveryJobCard.java
src/main/java/seedu/address/ui/timetable/CompleteWindow.java
src/main/java/seedu/address/ui/timetable/DayJobListPanel.java
src/main/java/seedu/address/ui/timetable/WeekJobListPanel.java
src/main/resources/view/AddDeliveryJobWindow.fxml
src/main/resources/view/CompletedJobWindow.fxml
src/main/resources/view/DayDeliveryJobListCard.fxml
src/main/resources/view/DayJobListPane.fxml
src/main/resources/view/DeliveryJobDetailPane.fxml
src/main/resources/view/DeliveryJobListCard.fxml
src/main/resources/view/MainWindow copy.fxml
src/main/resources/view/MainWindow.fxml
src/main/resources/view/UnscheduleWindow.fxml
src/test/java/seedu/address/logic/commands/AddCommandTest.java

* add a new window to show list of completed jobs
* add timetable_complete command to show list of completed jobs from Main Window
* add button to go to window of completed jobs from Main Window
* change UI: jobs with slot > 5 will be displayed as "Extra hours: 4PM++"

Add ability to show list of completed jobs

---

src/main/java/seedu/address/logic/commands/jobs/AddDeliveryJobCommand.java
src/main/java/seedu/address/logic/commands/jobs/CompleteDeliveryJobCommand.java
src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
src/main/java/seedu/address/logic/commands/timetable/TimetableCommand.java
src/main/java/seedu/address/logic/commands/timetable/TimetableCompletedCommand.java
src/main/java/seedu/address/logic/commands/timetable/TimetableDateCommand.java
src/main/java/seedu/address/logic/commands/timetable/TimetableUnscheduleCommand.java
src/main/java/seedu/address/logic/parser/jobs/AddDeliveryJobCommandParser.java
src/main/java/seedu/address/logic/parser/jobs/FindDeliveryJobCommandParser.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/jobs/DeliveryJob.java
src/main/java/seedu/address/model/jobs/Earning.java
src/main/java/seedu/address/model/jobs/sorters/SortbyTimeAndEarn.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/notification/NotificationManager.java

Let's
* dummy fix notification bug to launch app
* update add_job to make delivery date, slot, earning arguments optional
* update command result to display to users accordingly
* update sort method (in timetable window) to sort jobs based on date and then on earning

Update add_job command: Make delivery date, slot, earning optional

---

src/main/java/seedu/address/model/jobs/DeliverySlot.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
src/main/java/seedu/address/ui/jobs/DeliveryJobDetailPane.java
src/main/resources/view/AddDeliveryJobWindow.fxml
src/main/resources/view/DeliveryJobDetailPane.fxml
src/main/resources/view/DeliveryJobListPanel.fxml
src/main/resources/view/Extensions.css
src/main/resources/view/PersonListCard.fxml

Fix issue with opening duplicate create job window 

---

src/main/java/seedu/address/Main.java
src/main/java/seedu/address/storage/json/model/JsonAdaptedDeliveryJob.java
src/main/java/seedu/address/ui/jobs/DayDeliveryJobCard.java
src/main/java/seedu/address/ui/timetable/DayJobListPanel.java
src/main/java/seedu/address/ui/timetable/DayOfMonthPanel.java
src/main/java/seedu/address/ui/timetable/DayOfWeekPanel.java
src/main/java/seedu/address/ui/timetable/TimetableDetailPanel.java
src/main/resources/view/AddDeliveryJobWindow.fxml
src/main/resources/view/DayDeliveryJobListCard.fxml
src/main/resources/view/DayJobListPane.fxml
src/main/resources/view/DeliveryJobDetailPane.fxml
src/main/resources/view/DeliveryJobListPanel.fxml
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/TimetablePanel.fxml
src/main/resources/view/TimetableWindow.fxml

Timetable window is at default (bright) theme.
Change the window to dark theme makes it in sync with other windows.
Let's update timetable window to dark theme

Change timetable window to dark theme

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/stats/WeeklyStats.java
src/main/java/seedu/address/ui/StatisticsWindow.java
src/main/resources/view/StatisticsWindow.css
src/main/resources/view/StatisticsWindow.fxml
src/test/java/seedu/address/logic/commands/AddCommandTest.java

Resize statistics window
Display previous week's stats in stats window

Add previous week's stats to stats window

---

src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/Command.java
src/main/java/seedu/address/logic/commands/jobs/DeliveryJobCommand.java
src/main/java/seedu/address/logic/commands/jobs/ListDeliveryJobCommand.java
src/main/java/seedu/address/logic/commands/person/ListCommand.java
src/main/java/seedu/address/logic/commands/person/PersonCommand.java
src/main/java/seedu/address/logic/parser/DukeDriverParser.java
src/main/java/seedu/address/logic/parser/jobs/FindDeliveryJobCommandParser.java
src/main/java/seedu/address/model/jobs/DeliveryJob.java
src/main/java/seedu/address/model/jobs/DeliveryJobContainsKeywordsPredicate.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
src/main/java/seedu/address/ui/jobs/DeliveryJobDetailPane.java
src/main/java/seedu/address/ui/person/AddressBookWindow.java
src/main/resources/view/AddDeliveryJobWindow.fxml
src/main/resources/view/DeliveryJobDetailPane.fxml

Add parseCommandGroup for pre-checking.
Change command group implementation style to support static access.
Fix null pointer issue in find job command.
Fix IllegalArgumentException in find job command.
Remove case sensitivity for commands.

Add feedback for sort, filter action and detail pane.

---

src/main/java/seedu/address/logic/commands/jobs/FindDeliveryJobCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/jobs/FindDeliveryJobCommandParser.java
src/main/java/seedu/address/model/jobs/DeliveryJob.java
src/main/java/seedu/address/model/jobs/DeliveryJobContainsKeywordsPredicate.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/person/PersonCard.java

Remove case sensitive for find command
usage:
```
find_job ji/... si/... ri/... date/... slot/... done/ t | f
```

Add feedback for find_job command

---

src/main/java/seedu/address/logic/commands/jobs/DeleteDeliveryJobCommand.java
src/main/java/seedu/address/logic/parser/jobs/DeleteDeliveryJobCommandParser.java
src/main/java/seedu/address/logic/parser/jobs/EditDeliveryJobCommandParser.java

Add error message for delete command

Add optional args for edit cmd

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
src/main/java/seedu/address/ui/person/AddressBookWindow.java

FXML file URL is incorrect for AddressBookWindow and causes NullPointer
Fixing this will help to release jar file sucessfully.
Let's update FXML file URL in AddressBookWindow

Fix fxml file URL in AddressBookWindow

---

src/main/java/seedu/address/model/reminder/Reminder.java
src/main/java/seedu/address/model/reminder/ReminderList.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/ReminderListWindow.java
src/main/java/seedu/address/ui/notification/BackgroundNotificationScheduler.java
src/main/java/seedu/address/ui/notification/BackgroundReminderTask.java
src/main/java/seedu/address/ui/notification/BackgroundScheduleTask.java
src/main/java/seedu/address/ui/notification/NotificationManager.java

Notification fix

---

src/main/resources/view/StatisticsWindow.fxml

fix bug where stats window cut off stats

Increase stats window size
